[colors.bright]
black = "0x555753"
blue = "0x4a5a8d"
cyan = "0x12bccb"
green = "0x27a343"
magenta = "0x893c8c"
red = "0xc60001"
white = "0xeeeeec"
yellow = "0xd5a30e"

[colors.normal]
black = "0x2e3436"
blue = "0x425387"
cyan = "0x06989a"
green = "0x447241"
magenta = "0x965d98"
red = "0xa31604"
white = "0xd3d7cf"
yellow = "0xc1951a"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"
