#!/usr/bin/env sh

ps_bold="\[$(tput bold)\]"
ps_cyan="\[$(tput setaf 6)\]"
ps_reset="\[$(tput sgr0)\]"

PS1="[${ps_bold}\u${ps_reset}@${ps_bold}\h${ps_reset} ${ps_cyan}\W${ps_reset}]\$ "

unset ps_bold ps_cyan ps_reset

# Aliases
alias diff='diff --color=auto'
alias ls='ls --color=auto'
alias ip='ip -color=auto'
alias grep='grep --color=auto'

#alias doom-emacs="~/.config/emacs/bin/doom run"

if [ $SSH_CONNECTION ]; then
  # Vim over SSH connection
  export EDITOR='vim'
else
  # Neovim btw
  export EDITOR='nvim'
fi

export BUN_CONFIG_MAX_HTTP_REQUESTS=60
export http_proxy="http://127.0.0.1:7890/"
export ftp_proxy="ftp://127.0.0.1:7890/"
export rsync_proxy="rsync://127.0.0.1:7890/"
export no_proxy="localhost,127.0.0.1,192.168.1.1,::1,*.local"
export HTTP_PROXY="http://127.0.0.1:7890/"
export FTP_PROXY="ftp://127.0.0.1:7890/"
export RSYNC_PROXY="rsync://127.0.0.1:7890/"
export NO_PROXY="localhost,127.0.0.1,192.168.1.1,::1,*.local"
export https_proxy="http://127.0.0.1:7890/"
export HTTPS_PROXY="http://127.0.0.1:7890/"
